/**
 * Meta-Cognitive Types
 * 
 * Data structures for self-reflection, reasoning quality tracking,
 * and autonomous improvement.
 */

/**
 * A trace of reasoning/performance for a single event
 */
export interface ReasoningTrace {
  id: string;
  eventId: string;
  timestamp: number;
  eventType: string;
  
  // What I predicted would happen
  predictions?: {
    expectedOutcome: string;
    confidence: number;
    actualOutcome?: string;
    wasCorrect?: boolean;
  };
  
  // How I performed
  performance: {
    responseTime: number;
    surpriseScore?: number;
    userCorrection?: boolean;
    userSatisfaction?: number; // 0-1 if detectable
    retryCount?: number;
    errorOccurred?: boolean;
  };
  
  // What I learned (filled by MetaCognitiveEngine)
  insights?: {
    patternDetected?: string;
    confidenceDelta?: number;
    newHeuristic?: string;
    improvementArea?: string;
  };
  
  // Context for learning
  context: {
    timeOfDay: number; // hour 0-23
    dayOfWeek: number; // 0-6
    isWeekend: boolean;
    conversationId?: string;
    userAction?: string;
    sessionType?: string;
  };
  
  // Reflection status
  reflected?: boolean;
  reflectionTimestamp?: number;
}

/**
 * Lightweight metric event for batch queue
 */
export interface MetricEvent {
  eventId: string;
  eventType: string;
  responseTime: number;
  surpriseScore?: number;
  timestamp: number;
  batchId?: string;
  errorOccurred?: boolean;
  retryCount?: number;
}

/**
 * Aggregated performance metrics
 */
export interface PerformanceMetrics {
  totalEvents: number;
  avgResponseTime: number;
  p95ResponseTime: number;
  errorRate: number;
  avgSurpriseScore: number;
  topEventTypes: Array<{ type: string; count: number }>;
  hourlyDistribution: Array<{ hour: number; count: number }>;
  timeRange: {
    start: number;
    end: number;
  };
}

/**
 * A pattern detected by the meta-cognitive engine
 */
export interface DetectedPattern {
  id: string;
  type: 'temporal' | 'behavioral' | 'error' | 'success' | 'optimization';
  description: string;
  frequency: number;
  confidence: number;
  firstSeen: number;
  lastSeen: number;
  examples: string[];
  recommendation?: string;
}

/**
 * An insight generated by reflection
 */
export interface MetaInsight {
  id: string;
  timestamp: number;
  type: 'improvement' | 'strength' | 'pattern' | 'anomaly' | 'opportunity';
  title: string;
  description: string;
  evidence: string[];
  confidence: number;
  actionable: boolean;
  suggestedAction?: string;
  impact: 'low' | 'medium' | 'high';
  relatedPatterns: string[];
}

/**
 * Configuration for MetaCognitiveEngine
 */
export interface MetaCognitiveConfig {
  /** How often to run reflection (ms) - default: 6 hours */
  reflectionInterval?: number;
  /** Minimum events before reflection - default: 50 */
  minEventsForReflection?: number;
  /** Maximum events to analyze per reflection - default: 1000 */
  maxEventsPerReflection?: number;
  /** Database path for metrics */
  dbPath?: string;
  /** Enable automatic insight storage to MEMORY.md */
  storeInsightsToMemory?: boolean;
  /** Quiet hours for intensive analysis (don't run heavy analysis) */
  quietHours?: { start: number; end: number };
}

/**
 * Reflection report generated by meta-cognitive engine
 */
export interface ReflectionReport {
  timestamp: number;
  eventsAnalyzed: number;
  timeRange: { start: number; end: number };
  performance: PerformanceMetrics;
  patterns: DetectedPattern[];
  insights: MetaInsight[];
  recommendations: Array<{
    priority: 'low' | 'medium' | 'high';
    action: string;
    rationale: string;
    estimatedImpact: string;
  }>;
  nextReflectionDue: number;
}
